PyDemo:
  # 首次会根据接口数据包生成，可自行更改或添加新配置，所有配置将用于公共关联值。
  host: 10.88.88.141:20037
  headers:
    Content-Type: application/x-www-form-urlencoded;charset=UTF-8
  cookies:
  headtoken: xu5YwIZFkVGczMn0H0rot2ps7zRIbvrTHNwMXx1sJXg=
